import { db, financialProductsTable } from "@workspace/db";

const SEED_DATA = [
  { institutionName: "Bank of Bhutan (BOB)", productCategory: "savings", productName: "Savings Account", interestRate: "4.00%", minimumBalance: "Nu. 500", keyFeatures: "Largest branch network, mobile banking", sourceUrl: "https://www.bob.bt/personal-banking/", interestRateMin: 4.0, interestRateMax: 4.0, minimumBalanceValue: 500, productSubcategory: "regular_savings", targetSegment: "individual" },
  { institutionName: "Bhutan National Bank (BNB)", productCategory: "savings", productName: "Savings Account", interestRate: "4.25%", minimumBalance: "Nu. 1,000", keyFeatures: "Digital banking, SMS alerts", sourceUrl: "https://www.bnb.bt/savings-account/", interestRateMin: 4.25, interestRateMax: 4.25, minimumBalanceValue: 1000, productSubcategory: "regular_savings", targetSegment: "individual" },
  { institutionName: "Bhutan Development Bank (BDB)", productCategory: "savings", productName: "Savings Account", interestRate: "4.00%", minimumBalance: "Nu. 500", keyFeatures: "Rural focus, agricultural lending", sourceUrl: "https://www.bdbl.bt/products/", interestRateMin: 4.0, interestRateMax: 4.0, minimumBalanceValue: 500, productSubcategory: "regular_savings", targetSegment: "individual" },
  { institutionName: "T Bank", productCategory: "savings", productName: "Savings Account", interestRate: "4.50%", minimumBalance: "Nu. 1,000", keyFeatures: "Modern digital services", sourceUrl: "https://www.tbank.bt/personal-banking/", interestRateMin: 4.5, interestRateMax: 4.5, minimumBalanceValue: 1000, productSubcategory: "regular_savings", targetSegment: "individual" },
  { institutionName: "Druk PNB", productCategory: "savings", productName: "Savings Account", interestRate: "4.00%", minimumBalance: "Nu. 1,000", keyFeatures: "Joint venture, savings products", sourceUrl: "https://www.drukpnb.bt/deposits/", interestRateMin: 4.0, interestRateMax: 4.0, minimumBalanceValue: 1000, productSubcategory: "regular_savings", targetSegment: "individual" },

  { institutionName: "Bank of Bhutan", productCategory: "fd", productName: "Fixed Deposit — 1 Year", interestRate: "7.00%", minimumBalance: "Nu. 5,000", tenure: "1 year", keyFeatures: "Government-backed, reliable returns", sourceUrl: "https://www.bob.bt/personal-banking/", interestRateMin: 7.0, interestRateMax: 7.0, minimumBalanceValue: 5000, tenureMonthsMin: 12, tenureMonthsMax: 12, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "Bank of Bhutan", productCategory: "fd", productName: "Fixed Deposit — 2 Years", interestRate: "7.50%", minimumBalance: "Nu. 5,000", tenure: "2 years", keyFeatures: "Government-backed, reliable returns", sourceUrl: "https://www.bob.bt/personal-banking/", interestRateMin: 7.5, interestRateMax: 7.5, minimumBalanceValue: 5000, tenureMonthsMin: 24, tenureMonthsMax: 24, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "Bank of Bhutan", productCategory: "fd", productName: "Fixed Deposit — 3 Years", interestRate: "8.00%", minimumBalance: "Nu. 5,000", tenure: "3 years", keyFeatures: "Government-backed, reliable returns", sourceUrl: "https://www.bob.bt/personal-banking/", interestRateMin: 8.0, interestRateMax: 8.0, minimumBalanceValue: 5000, tenureMonthsMin: 36, tenureMonthsMax: 36, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "Bank of Bhutan", productCategory: "fd", productName: "Fixed Deposit — 5 Years", interestRate: "8.50%", minimumBalance: "Nu. 5,000", tenure: "5 years", keyFeatures: "Government-backed, reliable returns", sourceUrl: "https://www.bob.bt/personal-banking/", interestRateMin: 8.5, interestRateMax: 8.5, minimumBalanceValue: 5000, tenureMonthsMin: 60, tenureMonthsMax: 60, productSubcategory: "term_deposit", targetSegment: "individual" },

  { institutionName: "Bhutan National Bank", productCategory: "fd", productName: "Fixed Deposit — 1 Year", interestRate: "7.25%", minimumBalance: "Nu. 5,000", tenure: "1 year", keyFeatures: "Competitive rates, digital access", sourceUrl: "https://www.bnb.bt/fixed-deposit/", interestRateMin: 7.25, interestRateMax: 7.25, minimumBalanceValue: 5000, tenureMonthsMin: 12, tenureMonthsMax: 12, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "Bhutan National Bank", productCategory: "fd", productName: "Fixed Deposit — 2 Years", interestRate: "7.75%", minimumBalance: "Nu. 5,000", tenure: "2 years", keyFeatures: "Competitive rates, digital access", sourceUrl: "https://www.bnb.bt/fixed-deposit/", interestRateMin: 7.75, interestRateMax: 7.75, minimumBalanceValue: 5000, tenureMonthsMin: 24, tenureMonthsMax: 24, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "Bhutan National Bank", productCategory: "fd", productName: "Fixed Deposit — 3 Years", interestRate: "8.25%", minimumBalance: "Nu. 5,000", tenure: "3 years", keyFeatures: "Competitive rates, digital access", sourceUrl: "https://www.bnb.bt/fixed-deposit/", interestRateMin: 8.25, interestRateMax: 8.25, minimumBalanceValue: 5000, tenureMonthsMin: 36, tenureMonthsMax: 36, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "Bhutan National Bank", productCategory: "fd", productName: "Fixed Deposit — 5 Years", interestRate: "8.75%", minimumBalance: "Nu. 5,000", tenure: "5 years", keyFeatures: "Competitive rates, digital access", sourceUrl: "https://www.bnb.bt/fixed-deposit/", interestRateMin: 8.75, interestRateMax: 8.75, minimumBalanceValue: 5000, tenureMonthsMin: 60, tenureMonthsMax: 60, productSubcategory: "term_deposit", targetSegment: "individual" },

  { institutionName: "Bhutan Development Bank", productCategory: "fd", productName: "Fixed Deposit — 1 Year", interestRate: "6.75%", minimumBalance: "Nu. 1,000", tenure: "1 year", keyFeatures: "Low minimum deposit, rural accessibility", sourceUrl: "https://www.bdbl.bt/products/", interestRateMin: 6.75, interestRateMax: 6.75, minimumBalanceValue: 1000, tenureMonthsMin: 12, tenureMonthsMax: 12, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "Bhutan Development Bank", productCategory: "fd", productName: "Fixed Deposit — 2 Years", interestRate: "7.25%", minimumBalance: "Nu. 1,000", tenure: "2 years", keyFeatures: "Low minimum deposit, rural accessibility", sourceUrl: "https://www.bdbl.bt/products/", interestRateMin: 7.25, interestRateMax: 7.25, minimumBalanceValue: 1000, tenureMonthsMin: 24, tenureMonthsMax: 24, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "Bhutan Development Bank", productCategory: "fd", productName: "Fixed Deposit — 3 Years", interestRate: "7.75%", minimumBalance: "Nu. 1,000", tenure: "3 years", keyFeatures: "Low minimum deposit, rural accessibility", sourceUrl: "https://www.bdbl.bt/products/", interestRateMin: 7.75, interestRateMax: 7.75, minimumBalanceValue: 1000, tenureMonthsMin: 36, tenureMonthsMax: 36, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "Bhutan Development Bank", productCategory: "fd", productName: "Fixed Deposit — 5 Years", interestRate: "8.25%", minimumBalance: "Nu. 1,000", tenure: "5 years", keyFeatures: "Low minimum deposit, rural accessibility", sourceUrl: "https://www.bdbl.bt/products/", interestRateMin: 8.25, interestRateMax: 8.25, minimumBalanceValue: 1000, tenureMonthsMin: 60, tenureMonthsMax: 60, productSubcategory: "term_deposit", targetSegment: "individual" },

  { institutionName: "T Bank", productCategory: "fd", productName: "Fixed Deposit — 1 Year", interestRate: "7.50%", minimumBalance: "Nu. 10,000", tenure: "1 year", keyFeatures: "Highest rates, modern banking", sourceUrl: "https://www.tbank.bt/personal-banking/", interestRateMin: 7.5, interestRateMax: 7.5, minimumBalanceValue: 10000, tenureMonthsMin: 12, tenureMonthsMax: 12, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "T Bank", productCategory: "fd", productName: "Fixed Deposit — 2 Years", interestRate: "8.00%", minimumBalance: "Nu. 10,000", tenure: "2 years", keyFeatures: "Highest rates, modern banking", sourceUrl: "https://www.tbank.bt/personal-banking/", interestRateMin: 8.0, interestRateMax: 8.0, minimumBalanceValue: 10000, tenureMonthsMin: 24, tenureMonthsMax: 24, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "T Bank", productCategory: "fd", productName: "Fixed Deposit — 3 Years", interestRate: "8.50%", minimumBalance: "Nu. 10,000", tenure: "3 years", keyFeatures: "Highest rates, modern banking", sourceUrl: "https://www.tbank.bt/personal-banking/", interestRateMin: 8.5, interestRateMax: 8.5, minimumBalanceValue: 10000, tenureMonthsMin: 36, tenureMonthsMax: 36, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "T Bank", productCategory: "fd", productName: "Fixed Deposit — 5 Years", interestRate: "9.00%", minimumBalance: "Nu. 10,000", tenure: "5 years", keyFeatures: "Highest rates, modern banking", sourceUrl: "https://www.tbank.bt/personal-banking/", interestRateMin: 9.0, interestRateMax: 9.0, minimumBalanceValue: 10000, tenureMonthsMin: 60, tenureMonthsMax: 60, productSubcategory: "term_deposit", targetSegment: "individual" },

  { institutionName: "Druk PNB", productCategory: "fd", productName: "Fixed Deposit — 1 Year", interestRate: "7.00%", minimumBalance: "Nu. 5,000", tenure: "1 year", keyFeatures: "International banking standards", sourceUrl: "https://www.drukpnb.bt/deposits/", interestRateMin: 7.0, interestRateMax: 7.0, minimumBalanceValue: 5000, tenureMonthsMin: 12, tenureMonthsMax: 12, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "Druk PNB", productCategory: "fd", productName: "Fixed Deposit — 2 Years", interestRate: "7.50%", minimumBalance: "Nu. 5,000", tenure: "2 years", keyFeatures: "International banking standards", sourceUrl: "https://www.drukpnb.bt/deposits/", interestRateMin: 7.5, interestRateMax: 7.5, minimumBalanceValue: 5000, tenureMonthsMin: 24, tenureMonthsMax: 24, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "Druk PNB", productCategory: "fd", productName: "Fixed Deposit — 3 Years", interestRate: "8.00%", minimumBalance: "Nu. 5,000", tenure: "3 years", keyFeatures: "International banking standards", sourceUrl: "https://www.drukpnb.bt/deposits/", interestRateMin: 8.0, interestRateMax: 8.0, minimumBalanceValue: 5000, tenureMonthsMin: 36, tenureMonthsMax: 36, productSubcategory: "term_deposit", targetSegment: "individual" },
  { institutionName: "Druk PNB", productCategory: "fd", productName: "Fixed Deposit — 5 Years", interestRate: "8.50%", minimumBalance: "Nu. 5,000", tenure: "5 years", keyFeatures: "International banking standards", sourceUrl: "https://www.drukpnb.bt/deposits/", interestRateMin: 8.5, interestRateMax: 8.5, minimumBalanceValue: 5000, tenureMonthsMin: 60, tenureMonthsMax: 60, productSubcategory: "term_deposit", targetSegment: "individual" },

  { institutionName: "Bank of Bhutan", productCategory: "housing", productName: "Housing Loan", interestRate: "9.00% – 10.50%", tenure: "20 years", fees: "1% of loan", keyFeatures: "Max LTV 80%, largest housing lender", sourceUrl: "https://www.bob.bt/personal-banking/", interestRateMin: 9.0, interestRateMax: 10.5, tenureMonthsMin: 12, tenureMonthsMax: 240, feeValue: 1.0, productSubcategory: "housing_loan", targetSegment: "individual" },
  { institutionName: "Bhutan National Bank", productCategory: "housing", productName: "Housing Loan", interestRate: "9.25% – 10.75%", tenure: "20 years", fees: "1% of loan", keyFeatures: "Max LTV 80%, quick processing", sourceUrl: "https://www.bnb.bt/loans/", interestRateMin: 9.25, interestRateMax: 10.75, tenureMonthsMin: 12, tenureMonthsMax: 240, feeValue: 1.0, productSubcategory: "housing_loan", targetSegment: "individual" },
  { institutionName: "Bhutan Development Bank", productCategory: "housing", productName: "Housing Loan", interestRate: "8.75% – 10.25%", tenure: "25 years", fees: "0.75% of loan", keyFeatures: "Max LTV 85%, lowest processing fee", sourceUrl: "https://www.bdbl.bt/products/", interestRateMin: 8.75, interestRateMax: 10.25, tenureMonthsMin: 12, tenureMonthsMax: 300, feeValue: 0.75, productSubcategory: "housing_loan", targetSegment: "individual" },
  { institutionName: "NPPF", productCategory: "housing", productName: "Housing Loan", interestRate: "8.00% – 9.00%", tenure: "25 years", fees: "Minimal", keyFeatures: "Max LTV 90%, best rates for NPPF members", sourceUrl: "https://www.nppf.org.bt/services/", interestRateMin: 8.0, interestRateMax: 9.0, tenureMonthsMin: 12, tenureMonthsMax: 300, feeValue: 0, productSubcategory: "housing_loan", targetSegment: "individual" },
  { institutionName: "T Bank", productCategory: "housing", productName: "Housing Loan", interestRate: "9.50% – 11.00%", tenure: "15 years", fees: "1% of loan", keyFeatures: "Max LTV 75%, quick disbursal", sourceUrl: "https://www.tbank.bt/personal-banking/", interestRateMin: 9.5, interestRateMax: 11.0, tenureMonthsMin: 12, tenureMonthsMax: 180, feeValue: 1.0, productSubcategory: "housing_loan", targetSegment: "individual" },

  { institutionName: "Bank of Bhutan", productCategory: "personal", productName: "Personal Loan", interestRate: "12.00% – 14.00%", tenure: "5 years", keyFeatures: "Max Nu. 5,00,000, salary assignment collateral", sourceUrl: "https://www.bob.bt/personal-banking/", interestRateMin: 12.0, interestRateMax: 14.0, tenureMonthsMin: 12, tenureMonthsMax: 60, productSubcategory: "personal_loan", targetSegment: "individual" },
  { institutionName: "Bhutan National Bank", productCategory: "personal", productName: "Personal Loan", interestRate: "12.50% – 14.50%", tenure: "5 years", keyFeatures: "Max Nu. 5,00,000, salary assignment collateral", sourceUrl: "https://www.bnb.bt/loans/", interestRateMin: 12.5, interestRateMax: 14.5, tenureMonthsMin: 12, tenureMonthsMax: 60, productSubcategory: "personal_loan", targetSegment: "individual" },
  { institutionName: "Bhutan Development Bank", productCategory: "personal", productName: "Personal Loan", interestRate: "11.00% – 13.00%", tenure: "5 years", keyFeatures: "Max Nu. 3,00,000, guarantor collateral", sourceUrl: "https://www.bdbl.bt/products/", interestRateMin: 11.0, interestRateMax: 13.0, tenureMonthsMin: 12, tenureMonthsMax: 60, productSubcategory: "personal_loan", targetSegment: "individual" },
  { institutionName: "T Bank", productCategory: "personal", productName: "Personal Loan", interestRate: "13.00% – 15.00%", tenure: "4 years", keyFeatures: "Max Nu. 4,00,000, salary assignment collateral", sourceUrl: "https://www.tbank.bt/personal-banking/", interestRateMin: 13.0, interestRateMax: 15.0, tenureMonthsMin: 12, tenureMonthsMax: 48, productSubcategory: "personal_loan", targetSegment: "individual" },
  { institutionName: "Druk PNB", productCategory: "personal", productName: "Personal Loan", interestRate: "12.00% – 14.00%", tenure: "5 years", keyFeatures: "Max Nu. 5,00,000, property/salary collateral", sourceUrl: "https://www.drukpnb.bt/loans/", interestRateMin: 12.0, interestRateMax: 14.0, tenureMonthsMin: 12, tenureMonthsMax: 60, productSubcategory: "personal_loan", targetSegment: "individual" },

  { institutionName: "Bank of Bhutan", productCategory: "education", productName: "Education Loan", interestRate: "8.00% – 10.00%", tenure: "Repayment after course + 6 months", keyFeatures: "Max Nu. 10,00,000, parent guarantee", sourceUrl: "https://www.bob.bt/personal-banking/", interestRateMin: 8.0, interestRateMax: 10.0, productSubcategory: "education_loan", targetSegment: "individual" },
  { institutionName: "Bhutan National Bank", productCategory: "education", productName: "Education Loan", interestRate: "8.50% – 10.50%", tenure: "Repayment after course + 1 year", keyFeatures: "Max Nu. 8,00,000, parent guarantee", sourceUrl: "https://www.bnb.bt/loans/", interestRateMin: 8.5, interestRateMax: 10.5, productSubcategory: "education_loan", targetSegment: "individual" },
  { institutionName: "Bhutan Development Bank", productCategory: "education", productName: "Education Loan", interestRate: "7.50% – 9.50%", tenure: "Repayment after course + 1 year", keyFeatures: "Max Nu. 12,00,000, parent/property collateral", sourceUrl: "https://www.bdbl.bt/products/", interestRateMin: 7.5, interestRateMax: 9.5, productSubcategory: "education_loan", targetSegment: "individual" },
  { institutionName: "Royal Government Scholarship", productCategory: "education", productName: "Education Grant", interestRate: "0% (Grant)", tenure: "Service bond", keyFeatures: "Full tuition, no collateral required", sourceUrl: "https://www.education.gov.bt/scholarships/", interestRateMin: 0, interestRateMax: 0, productSubcategory: "scholarship", targetSegment: "individual" },
];

export async function seedFinancialProducts() {
  const existing = await db.select({ id: financialProductsTable.id }).from(financialProductsTable).limit(1);
  if (existing.length > 0) return;

  await db.insert(financialProductsTable).values(
    SEED_DATA.map(d => ({
      ...d,
      currency: "BTN",
      isActive: true,
      lastUpdated: new Date(),
    }))
  );
  console.log(`Seeded ${SEED_DATA.length} financial products`);
}
